### ISSUE TITLE
Pitchfork data available as a .csv?

### ISSUE THREAD

**Issue by mtheBee** [nolanbconaway/pitchfork-data#1]
Hi there, I'm teaching a statistics introductory course and wanted to use your Pitchfork data (found it on kaggle.com) for some student projects and demos. However, they're not advanced enough with programming to easily deal with sqlite files. Do you happen to have your dataset readily available in .csv form? If so, that would be a big help. Thanks!

**Comment by nolanbconaway** [comment]
Yes, of course. I am glad you are the data I collected for your class! 

It is straightforward to convert sqlite into csv. You can use a tool like [Sqlite Browser](http://sqlitebrowser.org/) to load the database and export the tables you want. 

There is also an [online tool](https://www.rebasedata.com/convert-sqlite-to-csv-online) capable of doing the conversion. You have options!

**Comment by mtheBee** [comment]
Thanks so much!

Best,
Maia
